name       : libtelepathy-glib
version    : 0.24.2
release    : 17
source     :
    - https://telepathy.freedesktop.org/releases/telepathy-glib/telepathy-glib-0.24.2.tar.gz : b0a374d771cdd081125f38c3abd079657642301c71a543d555e2bf21919273f0
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Telepathy is a D-Bus framework for unifying real time communication
description: |
    The Telepathy GLib contains a library used by GLib based Telepathy components. Telepathy is a D-Bus framework for unifying real time communication, including instant messaging, voice calls and video calls. It abstracts differences between protocols to provide a unified interface for applications.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - vala
setup      : |
    %configure --disable-static \
               --enable-vala-bindings \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
