name       : libtelepathy-glib
version    : 0.24.1
release    : 14
source     :
    - http://telepathy.freedesktop.org/releases/telepathy-glib/telepathy-glib-0.24.1.tar.gz : 9e0df1d8f857e0270cf0b32e2d1ca5a24aa7282873361785d573f72ad7f7d5eb
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Telepathy is a D-Bus framework for unifying real time communication
description: |
    The Telepathy GLib contains a library used by GLib based Telepathy components. Telepathy is a D-Bus framework for unifying real time communication, including instant messaging, voice calls and video calls. It abstracts differences between protocols to provide a unified interface for applications.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - vala
setup      : |
    %configure --disable-static \
               --enable-vala-bindings \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
